### ISSUE TITLE
No reference

### ISSUE THREAD

**Issue by Curt-Park** [convex-optimization-for-all/convex-optimization-for-all.github.io#105]
[1], [2] 등 레퍼런싱이 있으나 번호에 해당하는 레퍼런스가 없습니다.

<img width="489" alt="스크린샷 2021-05-16 오전 1 32 42" src="https://user-images.githubusercontent.com/14961526/118371239-9d3c1c80-b5e6-11eb-9142-b7b3985d45db.png">

https://convex-optimization-for-all.github.io/chapter01/

**Comment by enfow** [comment]
Issue resolved with PR #113
