### ISSUE TITLE
목차 not aligned

### ISSUE THREAD

**Issue by Curt-Park** [convex-optimization-for-all/convex-optimization-for-all.github.io#106]
챕터의 목차에서 다소 잘 정렬되지 못한 인상을 받았습니다.
예를 들어 챕터3의 경우 목차에서 03-01 없이 03-01-02가 등장합니다.

<img width="611" alt="스크린샷 2021-05-16 오전 1 34 36" src="https://user-images.githubusercontent.com/14961526/118371284-e2f8e500-b5e6-11eb-843b-ead2d25d9c59.png">

00-00-00 소챕터를 모두 00-00 레벨로 병합시키는 것도 방법일 것 같습니다.

**Comment by enfow** [comment]
@RRoundTable @YoungJaeChoung @LEEMINJOO @hunhoon21 @enfow 

1. 각자 맡은 챕터 빠진 부분 없는지 확인하기
2. 00 없는 경우 생성하기(있으면 옮기기)

**Comment by hunhoon21** [comment]
5, 18, 19, 20, 21 장은 확인 완료했습니다-!
![image](https://user-images.githubusercontent.com/36983960/118985255-430dd380-b9b9-11eb-8476-7e709c87aca1.png)
![image](https://user-images.githubusercontent.com/36983960/118985269-4608c400-b9b9-11eb-91be-ce769ff5cfb9.png)
![image](https://user-images.githubusercontent.com/36983960/118985279-4903b480-b9b9-11eb-987e-a063d6085bce.png)
![image](https://user-images.githubusercontent.com/36983960/118985292-4b660e80-b9b9-11eb-887c-3fe24c96476a.png)
![image](https://user-images.githubusercontent.com/36983960/118985306-4dc86880-b9b9-11eb-9cc5-ba9c2700a17e.png)

**Comment by Curt-Park** [comment]
## Not Aligned Chapters

<img width="667" alt="스크린샷 2021-05-22 오전 12 27 41" src="https://user-images.githubusercontent.com/14961526/119161647-86894000-ba94-11eb-8ca9-5aa465351f95.png">
<img width="582" alt="스크린샷 2021-05-22 오전 12 27 51" src="https://user-images.githubusercontent.com/14961526/119161666-8be68a80-ba94-11eb-968c-0196396e33b5.png">
<img width="582" alt="스크린샷 2021-05-22 오전 12 28 20" src="https://user-images.githubusercontent.com/14961526/119161749-9dc82d80-ba94-11eb-8c0a-793cba4f9238.png">

**Comment by Curt-Park** [comment]
@enfow 3, 4, 12장 각 담당자 분들 assign 부탁드립니다.

@LEEMINJOO @YoungJaeChoung @RRoundTable

**Comment by hunhoon21** [comment]
![image](https://user-images.githubusercontent.com/36983960/119217112-e9b9b780-bb12-11eb-842e-c4179916f1e8.png)
1장도 같은 이슈가 있네요
