### ISSUE TITLE
UI 제안

### ISSUE THREAD

**Issue by cneyang** [convex-optimization-for-all/convex-optimization-for-all.github.io#126]
기존 WikiDocs의 자료로 공부하고 있다가 변화된 자료를 새롭게 보게 되었습니다.
이전 포맷과 달라지면서 불편함을 느끼는 점이 있어 이슈 남깁니다.

1. 수식 정렬
[기존]
![image](https://user-images.githubusercontent.com/50402681/118917639-44fd7580-b96c-11eb-80b9-e53bbe3afdff.png)
[신규]
![image](https://user-images.githubusercontent.com/50402681/118917662-55155500-b96c-11eb-9224-0ac4df8b2432.png)

기존의 방식처럼 정렬이되면 보기 편할것 같습니다.

2. 폰트
기존의 폰트가 고딕체로 더 가독성이 높았다고 느끼는데 바꿀 수 있을까요?

**Comment by Curt-Park** [comment]
수식 정렬 방식에 대해서는 TF-KR에서 설문조사를 진행중입니다.
https://www.facebook.com/groups/TensorFlowKR/permalink/1489882951352758/

**Comment by RRoundTable** [comment]
@cneyang

안녕하세요. 
수식포맷에 대한 제안을 해주셔서 내부적으로 고민할 수 있는 계기가 되었습니다.

TF-KR에서 설문조사를 한 결과 제안해주셨던 포맷도 좋은 반응을 얻었으나 아래의 2번 수식포맷이 보편적으로 보기 편하다는 피드백을 받았습니다.

<img width="523" alt="스크린샷 2021-05-21 오후 1 27 23" src="https://user-images.githubusercontent.com/27891090/119590945-ad3ad400-be10-11eb-8476-15a81195b554.png">
link: https://www.facebook.com/groups/TensorFlowKR/permalink/1489882951352758/

따라서 앞으로 2번 수식포맷으로 변경하는 작업을 진행할 계획입니다. #147 
리뷰 감사드립니다. ^^

**Comment by Curt-Park** [comment]
@cneyang 
폰트의 경우 개개인마다 가독성에 대한 체감이 다를 수 있기 때문에 다수의 사람에게서 동일한 지적이 제기되거든 논의해보도록 하겠습니다.

**Comment by enfow** [comment]
Close it because of Related Issue #147.
