### ISSUE TITLE
목차 위치 변경 논의

### ISSUE THREAD

**Issue by Curt-Park** [convex-optimization-for-all/convex-optimization-for-all.github.io#129]
독자들이 첫 페이지에서 가장 많이 찾아볼 내용이 `목차`일텐데 저자 서문 및 저자 소개 등에 밀려서 너무 아래에 위치해 있는 것 같습니다.

편의를 위해 위키독스처럼 저자 소개 등을 위한 별도 페이지를 만들거나 혹은 목차 위치를 위로 올리면 어떨까요?

![스크린샷 2021-05-20 오후 8 54 33](https://user-images.githubusercontent.com/14961526/118974460-cfb29480-b9ad-11eb-9c98-39fd6afe5ccc.png)

**Comment by hunhoon21** [comment]
목차만 위로 올려보니 약간 어색한 느낌도 드네요
![image](https://user-images.githubusercontent.com/36983960/118991061-5e2f1200-b9be-11eb-9f94-749457e07180.png)

**Comment by hunhoon21** [comment]
이런식으로 앞에 어떤 내용들이 나올지 표기하는건 어떨까요?
![image](https://user-images.githubusercontent.com/36983960/118992846-f679c680-b9bf-11eb-9339-802b3ecfb8bb.png)

**Comment by Curt-Park** [comment]
@hunhoon21 제안하신 방법 또는 목차와 나머지 내용의 페이지를 분리하는 아이디어 사이에 어느것이 더 좋을지 논의해보면 좋겠습니다.
