### ISSUE TITLE
구글 검색 노출

### ISSUE THREAD

**Issue by hunhoon21** [convex-optimization-for-all/convex-optimization-for-all.github.io#13]
검색에 노출되게 하여 많은 사람들이 볼 수 있게끔 한다

**Comment by enfow** [comment]
@hunhoon21 완료되었나요?!??

**Comment by hunhoon21** [comment]
그때 구글검색은 조금 더 완성하고 노출시키게 하자는 의견이 있어 아직 진행하지 않았습니다 ㅎㅎ

**Comment by enfow** [comment]
넵 확인 감사합니다!ㅎㅎ

**Comment by Curt-Park** [comment]
@enfow 공개 전 논의가 필요합니다.

**Comment by Curt-Park** [comment]
검색결과 확인

![스크린샷 2021-05-18 오전 10 53 20](https://user-images.githubusercontent.com/14961526/118578684-8d2f6300-b7c7-11eb-8973-d3417e581e3e.png)
