### ISSUE TITLE
왼쪽 슬라이드바가 열린 상태에서는 가운데 정렬을 하지 못함

### ISSUE THREAD

**Issue by hunhoon21** [convex-optimization-for-all/convex-optimization-for-all.github.io#142]
* 슬라이드바 없을때
  * ![image](https://user-images.githubusercontent.com/36983960/119248597-2ea22480-bbcd-11eb-84f6-47fb121b8e33.png)
* 슬라이드바 있을때
  * ![image](https://user-images.githubusercontent.com/36983960/119248603-3cf04080-bbcd-11eb-93f2-d80656e446ac.png)

슬라이드 바가 있을때를 기준으로도 가운데 정렬이 되면 보기 좋을 것 같습니다

**Comment by Curt-Park** [comment]
사이드바 말씀이시죠?
별도 윈도우이므로 가운데 정렬이 유지되고 있긴 합니다.
낮은 수정 비용과 더불어 화면을 더 넓게쓰는 차원에서 왼쪽정렬로 변경하는 것도 괜찮을 것 같습니다.

**Comment by hunhoon21** [comment]
> 사이드바 말씀이시죠?
> 별도 윈도우이므로 가운데 정렬이 유지되고 있긴 합니다.
> 낮은 수정 비용과 더불어 화면을 더 넓게쓰는 차원에서 왼쪽정렬로 변경하는 것도 괜찮을 것 같습니다.

사이드 바를 제외하고 가운데로 정렬되면 보기 좋을것 같은데, 기존 가운데 정렬에서 사이드만큼 옆으로 밀리는게 어색해보이네요

**Comment by Curt-Park** [comment]
@hunhoon21 

> 낮은 수정 비용과 더불어 화면을 더 넓게쓰는 차원에서 왼쪽정렬로 변경하는 것도 괜찮을 것 같습니다.

사이드바를 고려하여 위치를 가운데로 유지하는 것보다 왼쪽 정렬을 하는 편이 변경비용이 더 낮으면서도 화면을 더 많이 활용할 수 있을 것 같은데 어떻게 생각하세요?

**Comment by hunhoon21** [comment]
> @hunhoon21
> 
> > 낮은 수정 비용과 더불어 화면을 더 넓게쓰는 차원에서 왼쪽정렬로 변경하는 것도 괜찮을 것 같습니다.
> 
> 사이드바를 고려하여 위치를 가운데로 유지하는 것보다 왼쪽 정렬을 하는 편이 변경비용이 더 낮으면서도 화면을 더 많이 활용할 수 있을 것 같은데 어떻게 생각하세요?

좋을것 같습니다! 다만 요건 실제로 봐야 판단할 수 있을것 같네요 ㅎㅎㅎ
