### ISSUE TITLE
수식 포맷 변경하기

### ISSUE THREAD

**Issue by RRoundTable** [convex-optimization-for-all/convex-optimization-for-all.github.io#147]
설문조사 결과 2번 수식 포맷이 좋다는 피드백을 받았습니다. 

이에 2번 형태로 수식을 변경해야합니다.

https://www.facebook.com/groups/TensorFlowKR/permalink/1489882951352758/

<img width="523" alt="스크린샷 2021-05-21 오후 1 27 23" src="https://user-images.githubusercontent.com/27891090/119603956-29d9ac80-be29-11eb-8ecc-a04256c9b277.png">

**Comment by hunhoon21** [comment]
17-20 PR 완료

**Comment by Curt-Park** [comment]
전체 챕터 변경 완료
