### ISSUE TITLE
Chapter2 이미지 깨짐

### ISSUE THREAD

**Issue by cneyang** [convex-optimization-for-all/convex-optimization-for-all.github.io#163]
Chapter2의 대부분의 이미지들이 깨져서 보이지 않습니다.
![image](https://user-images.githubusercontent.com/50402681/120966099-b6c52400-c7a0-11eb-9295-3389e4487f31.png)

**Comment by Curt-Park** [comment]
해결되었습니다.
![스크린샷 2021-06-08 오후 7 38 06](https://user-images.githubusercontent.com/14961526/121171127-0daa2680-c891-11eb-9350-df4f03ec28e1.png)
