### ISSUE TITLE
Chapter2 Next Post 없음

### ISSUE THREAD

**Issue by cneyang** [convex-optimization-for-all/convex-optimization-for-all.github.io#164]
중간 chapter가 끝나고 다음중간 chapter로 넘어갈때 Next Post가 없는 문제가 있습니다.

02-02-02에서 02-03으로의 링크 없음
![image](https://user-images.githubusercontent.com/50402681/120966196-da886a00-c7a0-11eb-96c3-277a1113c219.png)

**Comment by cneyang** [comment]
해당 문제는 하이퍼링크만 달면 될것 같아서 해보려했는데 contents 디렉토리내에 "related-posts"는 없는것 같습니다.
제가 수정하기는 어려운 부분인가요?

**Comment by Curt-Park** [comment]
@cneyang 
![스크린샷 2021-06-08 오후 7 32 42](https://user-images.githubusercontent.com/14961526/121170581-5f05e600-c890-11eb-9aef-031958e8b2cc.png)

각 포스트에 order를 설정하면 그 숫자에 따라 `Previous Post`와 `Next Post`가 표시되게끔 구현되어있습니다.
챕터 2 각 포스트의 order가 제대로 입력된 것으로 보아 다른 부분에 문제가 있는 것 같습니다.
현재 원인 분석 중입니다.
