### ISSUE TITLE
Chapter06 이미지 깨짐 현상

### ISSUE THREAD

**Issue by cneyang** [convex-optimization-for-all/convex-optimization-for-all.github.io#177]
Chapter06 이미지가 깨져서 수정하려고 보니 로컬호스트에서는 제대로 보이는 문제가 있습니다.

![image](https://user-images.githubusercontent.com/50402681/122331174-5b98eb80-cf6f-11eb-97c8-e8c68b2d6138.png)

![image](https://user-images.githubusercontent.com/50402681/122331144-50de5680-cf6f-11eb-82ba-8b36a601def5.png)

**Comment by enfow** [comment]
확인했습니다. 알려주셔서 감사합니다!

**Comment by enfow** [comment]
```
{{ site.baseurl  }}/img/chapter_img/chapter06/
```

site.baseurl 뒤에 white space가 2개 있는 것이 문제였던 것으로 보입니다(하나인 경우에는 잘 보입니다 - 06-03-04, Linear-convergence image). 수정하겠습니다. 감사합니다.

**Comment by Curt-Park** [comment]
<img width="798" alt="스크린샷 2021-07-12 오전 1 55 49" src="https://user-images.githubusercontent.com/14961526/125203652-497f4400-e2b4-11eb-86ef-9d57f868f5e7.png">

#184 머지 뒤에도 동일한 증상이 계속되고 있습니다.

**Comment by enfow** [comment]
@Curt-Park  확인했습니다. 수정하겠습니다.

**Comment by Curt-Park** [comment]
#185 머지 후에도 여전히 문제가 발생합니다.

**Comment by Curt-Park** [comment]
Solved
<img width="1241" alt="스크린샷 2021-07-16 오전 12 28 29" src="https://user-images.githubusercontent.com/14961526/125814701-aed754d4-3605-47ea-922d-cee3ceb12d9f.png">
