### ISSUE TITLE
06-06 Stochastic gradient descent 오타

### ISSUE THREAD

**Issue by sjnah** [convex-optimization-for-all/convex-optimization-for-all.github.io#181]
https://github.com/convex-optimization-for-all/convex-optimization-for-all.github.io/blob/19af85afd11d16e993c8dfb435c174004e2db485/contents/chapter06/_posts/21-03-20-06_05_stochastic_gradient_descent.md

Convergence of stochastic gradient descent 부분에서
SGD Cyclic rule의 update식과 Batch GD update식 notation에 오타가 있습니다. 

### As-is
---
line 50   |     \text{SGD Cycle rule : } \quad x^{(k+1)} = x^{(k)} - t_k \cdot \sum_{i=1}^{m} \nabla f_i (x^{(k+i-1)})
line 57   |     \text{GD Batch : }  \quad  x^{(k+m)} = x^{(k)} - t_k \cdot \sum_{i=1}^{m} \nabla f_i (x^{(k)})

### To-be
---
line 50   |     \text{SGD Cycle rule : } \quad x^{(k+m)} = x^{(k)} - t_k \cdot \sum_{i=1}^{m} \nabla f_i (x^{(k+i-1)})
line 57   |     \text{GD Batch : }  \quad  x^{(k+1)} = x^{(k)} - t_k \cdot \sum_{i=1}^{m} \nabla f_i (x^{(k)})

**Comment by enfow** [comment]
감사합니다. 반영하도록 하겠습니다!
