### ISSUE TITLE
docker-compose makes all easier

### ISSUE THREAD

**Issue by Curt-Park** [convex-optimization-for-all/convex-optimization-for-all.github.io#21]
Like [Makinarocks blog](https://github.com/makinarocks/makinarocks.github.io/blob/master/docker-compose.yml), we can set [docker-compose.yml](https://urre.me/writings/docker-compose-and-jekyll/) so that people can set the environment easier. 

`$ docker-compose up`

**Comment by enfow** [comment]
Thank you for noti 😏
