### ISSUE TITLE
[Settings] Code Owner 제도 도입하기

### ISSUE THREAD

**Issue by enfow** [convex-optimization-for-all/convex-optimization-for-all.github.io#22]
Blog의 원할하고 안정적인 관리를 위해 Code Owner 시스템을 도입하려 합니다.

**Comment by Curt-Park** [comment]
FYI,
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by enfow** [comment]
PR merged.
