### ISSUE TITLE
[migration] jekyll 설치작업이 혼란스러울수 있음.

### ISSUE THREAD

**Issue by RRoundTable** [convex-optimization-for-all/convex-optimization-for-all.github.io#3]
jekyll 설치하는 과정과 버전에 대한 이슈가 발생할 수 있어 보입니다.

조금 더 간략하게 통일된 jekyll을 설치할 수 있는 방법을 같이 고민해보면 좋을 것 같습니다.

**Comment by Curt-Park** [comment]
https://github.com/convex-optimization-for-all/convex-optimization-for-all.github.io/pull/1

Pull Request에서 수정사항 리뷰중입니다.

**Comment by RRoundTable** [comment]
네 PR comment 확인했습니다.

migrator분들도 함께 고민해보면 좋을 것이라고 생각해서, 이슈로 남겼습니다.

**Comment by Curt-Park** [comment]
네, PR <-> Issue 연결 차원에서 댓글 남겼습니다.

**Comment by enfow** [comment]
docker-compose 추가로 해결되었다고 판단하여 클로즈합니다.
