### ISSUE TITLE
디렉토리 컨벤션

### ISSUE THREAD

**Issue by YoungJaeChoung** [convex-optimization-for-all/convex-optimization-for-all.github.io#7]
```
[ 기존 ]

chapter01
| - _posts
  | - 20-01-08-text.md
| - index.html


[ 제안: 띄어쓰기 없음 ]

chapter01
|- _posts
   |- 20-01-08-text.md
|- index.html
```

**Comment by enfow** [comment]
@YoungJaeChoung  두 가지의 차이점을 잘 모르겠습니다ㅠ 다시 한 번 알려주실 수 있나요?

**Comment by hunhoon21** [comment]
해당 이슈 추가로 논의할게 남아있나요?

**Comment by Curt-Park** [comment]
제안주신 이유를 좀 더 상세히 덧붙여주실 수 있으실까요?

<img width="1413" alt="스크린샷 2021-05-23 오후 12 57 52" src="https://user-images.githubusercontent.com/14961526/119247651-7d988b80-bbc6-11eb-9746-e629329595f9.png">

**Comment by YoungJaeChoung** [comment]
> 제안주신 이유를 좀 더 상세히 덧붙여주실 수 있으실까요?
> 
> <img alt="스크린샷 2021-05-23 오후 12 57 52" width="1413" src="https://user-images.githubusercontent.com/14961526/119247651-7d988b80-bbc6-11eb-9746-e629329595f9.png">

오래 전 것이라 기억이 정확히 안나네요

| 다음에 뛰어쓰기 후 - 표시가 나와서 가독성이 떨어져서 제안한 것 같은데 
저녁에 다시 확인해보겠습니다.

**Comment by enfow** [comment]
Closed.
