### ISSUE TITLE
블로그 컨셉 컬러 정하기

### ISSUE THREAD

**Issue by enfow** [convex-optimization-for-all/convex-optimization-for-all.github.io#80]
- 블로그 컨셉 컬러를 정하면 좋을 것 같습니다.
- 하이퍼링크 컬러 등에 적용해보고자 합니다.

**Comment by YoungJaeChoung** [comment]
(슬랙에 남긴 내용을 가져왔습니다)

하이퍼링크 색 관련 ㅡ 김영호 박사님, 현우님, 경현님 께서 주신 의견입니다.
1. 주황 (또는 회색)
    https://reinforcement-learning-kr.github.io/
2. 밑줄 + 굵기 바꿈 (색깔은 글 색과 같음)
    https://edwardtufte.github.io/tufte-css/

김영호 박사님도 개인적으로 파란색 컬러를 안좋아한다고 하십니다.
- 이유는 파란색이 인간이 인지하기 안좋은 색이기 때문입니다. (번짐 효과를 뇌에 줌)
> 색깔 참고용 사이트: adobe colors
1) adobe color 사이트 접속: https://color.adobe.com/ko/explore
2) ‘탐색’ 메뉴 선택
3) ‘보기 > 색상 테마 > 인기도순’ 선택
