### ISSUE TITLE
[Closed] Chapter에 대한 전반적인 설명 포스트 순서 변경필요

### ISSUE THREAD

**Issue by LEEMINJOO** [convex-optimization-for-all/convex-optimization-for-all.github.io#92]
* 문제 상황
  * Chapter에 대한 전반적인 설명 포스트가 안보임
  * (좌) 12장 설명 위키독스 (우) 12장 깃블로그
  * <img width="1440" alt="스크린샷 2021-05-01 오후 4 07 58" src="https://user-images.githubusercontent.com/42792260/116774412-679c1d00-aa97-11eb-8f9d-4cec17d21ed7.png">

* 이유
  * 전반적인 설명 포스트는 12-01 과 같이 뒤에 번호가 없음
  * 챕터 가장 마지막에 전반적인 설명 포스트가 생김

**Comment by LEEMINJOO** [comment]
헉 main 브랜치를 안땡겨서 그렇네요,,

**Comment by LEEMINJOO** [comment]
Main 을 merge해도 동일한 문제가 있습니다.
<img width="1440" alt="스크린샷 2021-05-01 오후 4 16 31" src="https://user-images.githubusercontent.com/42792260/116774602-a41c4880-aa98-11eb-99a0-124d28c985f7.png">

**Comment by hunhoon21** [comment]
이거 해결 된거죠?

**Comment by Curt-Park** [comment]
해결 되었으므로 close합니다.
