### ISSUE TITLE
Main branch Warning message

### ISSUE THREAD

**Issue by LEEMINJOO** [convex-optimization-for-all/convex-optimization-for-all.github.io#94]
* md 파일에서 post_url 주소에 chaper번호가 안써있습니다.

<img width="1026" alt="스크린샷 2021-05-01 오후 4 14 44" src="https://user-images.githubusercontent.com/42792260/116774560-5b648f80-aa98-11eb-910c-67c5c857c837.png">

**Comment by enfow** [comment]
확인해보겠습니다. 감사합니다!

**Comment by enfow** [comment]
Resolved Issue with PR #97
