### ISSUE TITLE
[Suggestion] One more hierarchy to organize chapter posts

### ISSUE THREAD

**Issue by Curt-Park** [convex-optimization-for-all/convex-optimization-for-all.github.io#96]
현재 챕터 디렉토리가 너무 많아 파일 구조가 한 눈에 들어오지 않습니다.
모든 챕터를 한 디렉토리 아래로 묶어두면 어떨까요?

<img width="950" alt="스크린샷 2021-05-02 오전 12 11 28" src="https://user-images.githubusercontent.com/14961526/116786706-1877db80-aadb-11eb-87a4-f3d31214ca06.png">

**Comment by enfow** [comment]
contents라는 Directory를 하나 만들고 chapter 디렉토리들을 모두 넣는 것도 좋을 것 같습니다.

다만 현재 개별 포스팅의 링크들이 대부분 절대경로로 되어 있을텐데(convention) 변경이 최소화되는 방법을 찾아보는 것이 좋겠습니다.

**Comment by hunhoon21** [comment]
눈에 보이는 바로는, 
* `link chapter00`
* `% post_url chapter00`
* `https://convex-optimization-for-all.github.io/chapter00`
* `(/chapter00`
키워드로 검색하면 대부분의 경로이동을 커버하는것 같습니다.
각각의 `chapter00` 을 `contents/chapter00` 로 수정하면 될것 같은데, 어떠신가요? (일괄 수정 후 코드오너들이 각 장을 살펴보면 될것 같기도 하구요)

**Comment by Curt-Park** [comment]
@enfow 변경 여부에 대해 결정 부탁드립니다.
